// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdI0ZfVQIkHgE8RJt_6zLyuPo2v8t3Ddo',
    appId: '1:725137144668:web:9729962b4794b5770e1f99',
    messagingSenderId: '725137144668',
    projectId: 'legwork-jessedancr',
    authDomain: 'legwork-jessedancr.firebaseapp.com',
    storageBucket: 'legwork-jessedancr.firebasestorage.app',
    measurementId: 'G-NXJ07CKE29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpwFiBEg0onTH1lEsxHP0WZIPj6r5jnQ',
    appId: '1:725137144668:android:8f915abb9fed49520e1f99',
    messagingSenderId: '725137144668',
    projectId: 'legwork-jessedancr',
    storageBucket: 'legwork-jessedancr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-b9ncnNmlYl1DOtvpEHF1kF-LsFeOL8',
    appId: '1:725137144668:ios:5d0ee954d0544a820e1f99',
    messagingSenderId: '725137144668',
    projectId: 'legwork-jessedancr',
    storageBucket: 'legwork-jessedancr.firebasestorage.app',
    iosBundleId: 'com.example.legwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdI0ZfVQIkHgE8RJt_6zLyuPo2v8t3Ddo',
    appId: '1:725137144668:web:7e4f62e8a90749840e1f99',
    messagingSenderId: '725137144668',
    projectId: 'legwork-jessedancr',
    authDomain: 'legwork-jessedancr.firebaseapp.com',
    storageBucket: 'legwork-jessedancr.firebasestorage.app',
    measurementId: 'G-BRDDV6S6R5',
  );
}
