final List locations = [
  ['Agege', false],
  ['Ajeromi-Ifelodun', false],
  ['Alimosho', false],
  ['Amuwo-Odofin', false],
  ['Apapa', false],
  ['Badagry', false],
  ["Epe", false],
  ['Eti-osa', false],
  ['Ibeju-Lekki', false],
  ['Ifako-Ijaiye', false],
  ['Ifako-Gbagada', false],
  ['Ikeja', false],
  ['Ikorodu', false],
  ['Kosofe', false],
  ['Mushin', false],
  ['Ojo', false],
  ['Oshodi-isolo', false],
  ['Somolu', false],
  ['Surulere', false],
  ["Bariga", false],
  ['Ejigbo', false],
  ['Ikoyi-Obalende', false],
  ['Isolo', false],
  ['Victoria island', false],
  ['Lagos Island', false],
  ['Onigbongbo', false],
  ['Surulere', false],
  ['Yaba', false],
  ['Lekki', false],
  ['Epe', false],
  ['Egbeda', false],
];
